### ISSUE TITLE
make map stand alone

### ISSUE THREAD

**Issue by lbehm** [HackspaceJena/krautspace-rc3-map#2]
Damit die Map ohne rC3 spezifische Besonderheiten auskommt und auf https://kraut.world/ die primäre Online-Meeting-Platform für den Krautspace werden kann, schlage ich ein paar Anpassungen vor:

- Links zu anderen Maps entfernen
- Jitsi-Area auf den Haupt-Raum ausweiten (also rings um die Säule, Sitzbereich, ohne Werkstatt/Bar) damit man sich etwas bewegen kann und trotzdem im Jitsi unterhalten kann
- Spawn-Point eventuell in OG verlegen um schneller andere zu finden

Diskussion ist gewünscht ;)

**Comment by ghost** [comment]
> * Links zu anderen Maps entfernen

Zukünftig soll man mapübergreifend springen können, aber das ist Zukunftsmusik. Also vorerst raus damit.

> * Jitsi-Area auf den Haupt-Raum ausweiten (also rings um die Säule, Sitzbereich, ohne Werkstatt/Bar) damit man sich etwas bewegen kann und trotzdem im Jitsi unterhalten kann

Ein oder zwei Jitsis? Oder evtl. noch eins in der Werkstatt?

> * Spawn-Point eventuell in OG verlegen um schneller andere zu finden

Der Sinn der Karte ist auch, die Umgebung des Spaces nah genug abzubilden, sodass man schneller hin findet, wenn mensch mal physisch hin gehen möchte.

**Comment by lbehm** [comment]
> Ein oder zwei Jitsis?

In den letzten Diskussionen kam der Einwand, dass man auch mal kleine Gespräche führen möchte (Stichwort Breakout-Rooms). Ausreichend Spaces ohne Jitsi vorzusehen wäre da durchaus sinnvoll.

**Comment by ghost** [comment]
> In den letzten Diskussionen kam der Einwand, dass man auch mal kleine Gespräche führen möchte (Stichwort Breakout-Rooms). Ausreichend Spaces ohne Jitsi vorzusehen wäre da durchaus sinnvoll.

Vielleicht kommt früher oder später doch noch BBB-Support dazu. Ich wüsste gar nicht, ob es in Jitsi Break-Out Sessions überhaupt gibt.

**Comment by lbehm** [comment]
closing ticket because repo is archived
